title: Arkin Solomon
email: arkin@arkinsolomon.net
description: >-
  Arkin Solomon's projects and blogs
baseurl: ""
url: "https://arkinsolomon.net"
plugins:
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll_inline_highlight
destination: '_site'
include:
  - _pages
exclude:
  - readme.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - liquidhighlight.py
jekyll-minifier:
  uglifier_args:
    harmony: true
sass:
  style: compressed
theme: jekyll-theme-cayman
