title: Arkin Solomon
email: arkinsolomon@gmail.com
description: >-
Arkin Solomon's projects and blogs
baseurl: ""
url: "https://arkinsolomon.github.io"
plugins:
  - jekyll-seo-tag
  - jekyll-minifier
destination: '_site'
include:
  - _pages
exclude:
  - readme.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
jekyll-minifier:
  uglifier_args:
    harmony: true
theme: ''
sass:
  style: compressed

theme: jekyll-theme-cayman
