name: Site build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build site
        run: |
          git fetch --all
          git checkout origin/master
          
          sudo apt-get update
          sudo apt-get install ruby
          sudo gem install bundler
          git branch test-branch

          sudo bundle install
          bundle exec jekyll build

          mkdir -p ../tmp/.git

          ls -la

          cp -a _site/. ../tmp/
          rm -rf *
          cp -a ../tmp/. .

          touch .nojekyll
          ls -al
           
          git merge -s ours gh-pages
          git checkout gh-pages
          git merge master
