name: Site build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build site
        run: |
          sudo apt-get update
          sudo apt-get install ruby
          sudo gem install bundler
          git branch test-branch

          bundle install
          bundle exec jekyll build

          mkdir -p ../tmp/.git

          ls -la

          cp -a _site/. ../tmp/
          cp .git/ ../tmp
          rm -rf *
          cp -a ../tmp/. .

          touch .nojekyll
          ls -al
      - uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: "Site build"
          branch: test-branch
          add_options: '-f'
          push_options: '-f'