name: Build and deploy Jekyll site to GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          jekyll_build_options: '-V'
          pre_build_commands: apk add --update nodejs npm
          target_branch: 'gh-pages'
