name: Site build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          bundler: "Gemfile.lock"
          bundler-cache: true

      - name: Build/Push site
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git fetch --all
          git checkout gh-pages
          git checkout master
          git merge --allow-unrelated-histories -s ours gh-pages
          git checkout gh-pages
          git merge --allow-unrelated-histories master
          
          git branch test-branch

          sudo bundle install
          bundle exec jekyll build

          mkdir -p ../tmp/.git

          ls -la

          cp -a _site/. ../tmp/
          rm -rf *
          cp -a ../tmp/. .

          touch .nojekyll
          ls -al
           
          git commit -a -m "Update site"
          git push -f -u origin gh-pages
