name: Minify JavaScript files
on:
  push:
    branches: [ gh_pages ]
    
jobs:
  minify-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      
      - name: Run a multi-line script
        run: |
          npm install -g minify-all-js
          minify-all-js .
